name: hridhaya
description: "Hridhaya – Listening to the heart's silent whispers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: any
  shared_preferences: ^2.5.4
  vibration: any
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hridhaya_logo.png
